image: yxdhde/alpine-curl-git

stages:
  - build
  - deploy

hosts:
  stage: build
  script: ./generate >hosts
  artifacts:
    untracked: true

master-push:
  stage: deploy
  script: ./.master-push.sh
  dependencies: [hosts]
  only: [commander]
