image: vergissberlin/alpine-development

stages:
  - build
  - deploy

test:
  stage: build
  script: make

download:
  stage: build
  script:
    - ./hostcamo download
  artifacts:
    untracked: true

hosts:
  stage: deploy
  dependencies: [download]
  script:
    - mkdir -p dist
    - ./hostcamo recombinate > dist/hosts
  artifacts:
    paths: [dist/]

history-push:
  stage: deploy
  dependencies: [download]
  only: [master]
  script:
    - git config user.name "CI"
    - git config user.email "ci@example.com"
    - make ci-history
    - git push --quiet "${CI_REPOSITORY_URL/\/\/*@///oauth:$ACCESS_TOKEN@}"
