image: yxdhde/alpine-curl-git

stages:
  - build
  - deploy

test:
  stage: build
  script: make

hosts:
  stage: build
  script: ./hostcamo >hosts
  artifacts:
    untracked: true

master-push:
  stage: deploy
  script: ./.master-push.sh
  dependencies: [hosts]
  only: [commander]
