image: yxdhde/alpine-curl-git

stages:
  - build
  - deploy

hosts.new:
  stage: build
  script: ./generate >hosts.new
  artifacts:
    untracked: true

master-push:
  stage: deploy
  script: ./.master-push.sh
  dependencies: [hosts.new]
  only: [commander]
