image: vergissberlin/alpine-development

stages:
  - build
  - deploy

test:
  stage: build
  image: ruby:alpine
  before_script:
    - apk --no-cache add bash
    - gem install bashcov
  script: bashcov tests/.bash_unit tests/*

shellcheck:
  stage: build
  image: koalaman/shellcheck-alpine
  script: shellcheck hostcamo tests/*

hosts:
  stage: build
  script:
    - mkdir -p dist
    - ./hostcamo -c build >dist/hosts
  artifacts:
    untracked: true

history-push:
  stage: deploy
  dependencies: [hosts]
  only: [master]
  script:
    - git config user.name "CI"
    - git config user.email "ci@example.com"
    - make history MESSAGE="[CI:${CI_PIPELINE_SOURCE}] ${CI_COMMIT_SHA:0:8}"
    - git push --quiet "${CI_REPOSITORY_URL/\/\/*@///oauth:$ACCESS_TOKEN@}"
