image: yxdhde/alpine-curl-git

stages:
  - build
  - deploy

test:
  stage: build
  script: make

hosts:
  stage: build
  script: ./hostcamo
  artifacts:
    untracked: true

master-push:
  stage: deploy
  dependencies: [hosts]
  only: [commander]
  script:
    - git config user.name "CI"
    - git config user.email "ci@example.com"
    - make ci-master
    - git push --quiet "${CI_REPOSITORY_URL/\/\/*@///oauth:$ACCESS_TOKEN@}"
