image: vergissberlin/alpine-development

stages:
  - build
  - deploy

test:
  stage: build
  image: ruby:slim
  before_script:
    - gem install bashcov
  script:
    # bashcov cannot run as root so here's a magic user
    - useradd -s /bin/bash user
    - su user -c "$(command -v bashcov) tests/.bash_unit tests/*"
  coverage: '/\(\d+\.\d+%\) covered/'
  artifacts:
    untracked: true

shellcheck:
  stage: build
  image: koalaman/shellcheck-alpine
  script: shellcheck hostcamo tests/*

hosts:
  stage: build
  script:
    - mkdir -p dist
    - ./hostcamo -c build >dist/hosts
  artifacts:
    untracked: true

docker-push:
  stage: deploy
  image: "docker:latest"
  services: ["docker:dind"]
  variables:
    DOCKER_DRIVER: overlay2
  dependencies: [hosts]
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - DOCKER_IMAGE="${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG/master/latest}"
    - docker build . -t "$DOCKER_IMAGE"
    - docker push "$DOCKER_IMAGE"

history-push:
  stage: deploy
  dependencies: [hosts]
  only: [master]
  script:
    - git config user.name "CI"
    - git config user.email "ci@example.com"
    - make history MESSAGE="[CI:${CI_PIPELINE_SOURCE}] ${CI_COMMIT_SHA:0:8}"
    - git push --quiet "${CI_REPOSITORY_URL/\/\/*@///oauth:$ACCESS_TOKEN@}"
