image: vergissberlin/alpine-development

stages:
  - build
  - deploy

test:
  stage: build
  script: make

hosts:
  stage: build
  script:
    - mkdir -p dist
    - ./hostcamo > dist/hosts
  artifacts:
    untracked: true

history-push:
  stage: deploy
  dependencies: [hosts]
  only: [commander]
  script:
    - git config user.name "CI"
    - git config user.email "ci@example.com"
    - make ci-history
    - git push --quiet "${CI_REPOSITORY_URL/\/\/*@///oauth:$ACCESS_TOKEN@}"
