#!/bin/bash

target_ip=255.255.255.255
cache_dir=

ignore_hosts=(
  localhost.localdomain
  local
  localhost
  broadcasthost
  0.0.0.0
)

# Ripped this list from Pi-Hole:
# https://github.com/pi-hole/pi-hole/blob/9fe687bd62a7adb9b7f5f56b58e2823ee58d8fbc/automated%20install/basic-install.sh#L1129
hostfiles=(
  'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts'
)

trap 'pkill -P $$' exit

function panic {
  echo "$@" >&2
  exit 1
}

function init_opts {
  while getopts ":c:" opt "$@"; do
    case "$opt" in
      c) cache_dir="${OPTARG}";;
      *) panic "Err: $opt";;
    esac
  done
}

function as_filename {
  no_prefix="${1#http*://}"
  echo "${no_prefix//\//--}"
}

function extract_domains {
  re_ip='[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
  re_domain='[-.a-z0-9]+\.[a-z]{2,}'
  sed -E -n -e "s/^($re_ip)?([[:space:]]+)?($re_domain).*$/\3/p"
}

function join_by {
  local IFS="$1"
  shift
  echo "$*"
}

function reject {
  grep -F -v -x -f <(join_by $'\n' "$@")
}

function maybe_cache {
  if [ -z "$cache_dir" ]; then
    cat
  else
    mkdir -p "$cache_dir"
    tee "$cache_dir/$(as_filename "$1")"
  fi
}

function process_all {
  for url in "$@"; do
    curl --progress-bar -L "$url" | extract_domains | reject "${ignore_hosts[@]}" | maybe_cache "$url" &
  done
  wait
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  init_opts "$@"
  process_all "${hostfiles[@]}" | sort -u | sed -e "/^$/d" -e "s/^/$target_ip /"
fi
