#!/bin/bash

target_ip=255.255.255.255
build_dir=build

whitelist=(
  localhost.localdomain
  local
  localhost
  broadcasthost
  0.0.0.0
)

# Ripped this list from Pi-Hole:
# https://raw.githubusercontent.com/pi-hole/pi-hole/master/adlists.default
hostfiles=(
  https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  https://mirror1.malwaredomains.com/files/justdomains
  http://sysctl.org/cameleon/hosts
  https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
  https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
  https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  https://hosts-file.net/ad_servers.txt
)

function as_filename {
  <<<"$1" sed -e "s~^https*://~~" -e "s:/:--:g"
}

function strip {
  regex_ip='[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
  sed -E -e "s/^($regex_ip)?[[:space:]]+//g" -e 's/[[:space:]]*(#.*)?$//g'
}

function filter {
  regex_whitelist="($(sed -e 's#\.#\\.#g' -e 's# #|#g' <<<"${whitelist[@]}"))"
  sed -E -e "/^$regex_whitelist$/d" -e "/^[-._a-zA-Z0-9]+$/!d"
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  mkdir -p "$build_dir"
  for url in "${hostfiles[@]}"; do
    filename="$build_dir/$(as_filename "$url")"
    { curl -s "$url" | strip | filter | sort -u > "$filename"; } &
  done
  wait

  cat "$build_dir"/* | sort -u | sed -e "s/^/$target_ip /"
fi
