name: CI

on:
  push:
    #branches: [ $default-branch ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container: 'ruby:latest'
    steps:
      - uses: actions/checkout@v4
      - run: 'bundle install bashcov'
      - run: 'bashcov tests/.bash_unit tests/*'

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca
      - run: 'shellcheck hostcamo tests/*'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p dist
          ./hostcamo -c build >dist/hosts
