name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container: 'ruby:latest'
    steps:
      - uses: actions/checkout@v4
      - run: 'gem install bashcov'
      - env:
          COVERAGE: true
        run: 'make test'

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca
      - run: 'make lint'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: 'make build'
